/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.2.2/userguide/java_library_plugin.html
 */

plugins {
    `java-library`
}

repositories {
    jcenter()
}

dependencies {

    //Dependence to the demo inside package test
    testImplementation("io.github.vincenzopalazzo:material-ui-swing:1.1.1_pre-release_6.1")
}
