/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.linklabelui;


import io.linklabelui.view.LinkLabelUI;
import mdlaf.utils.MaterialColors;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

public class StandardSwingLinkLabel extends JPanel {

    protected JLabel linkToVincentGithub;
    protected JLabel linkToMaterialTheme;
    protected JLabel linkToMaterialToast;
    protected JLabel linkToDonation;

    protected MouseListener followingLink;

    public StandardSwingLinkLabel() {
        intView();
    }

    protected void intView() {
        initComponent();
        initAction();

        setVisible(true);
    }

    private void initComponent() {
        String starHtml = "<html><a href=''>";
        String endHtml = "</a></html>";
        linkToVincentGithub = new JLabel(starHtml + "Author library @vincenzopalazzo" + endHtml);
        linkToMaterialTheme = new JLabel(starHtml + "Go to material-ui-swing project" + endHtml);
        linkToMaterialToast = new JLabel(starHtml + "Go to toast project" + endHtml);
        linkToDonation = new JLabel(starHtml + "Support this project" + endHtml);

        linkToVincentGithub = new JLabel("Author library @vincenzopalazzo");
        linkToVincentGithub.setUI(new LinkLabelUI());

        super.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        super.add(Box.createRigidArea(new Dimension(5, 15)));
        super.add(linkToVincentGithub);
        super.add(Box.createRigidArea(new Dimension(5, 15)));

        super.add(linkToMaterialTheme);
        super.add(Box.createRigidArea(new Dimension(5, 15)));

        super.add(linkToMaterialToast);
        super.add(Box.createRigidArea(new Dimension(5, 15)));

        super.add(linkToDonation);
        super.add(Box.createRigidArea(new Dimension(5, 15)));
    }

    private void initAction() {
        followingLink = new ActionFollowingLink();
        linkToVincentGithub.addMouseListener(followingLink);
        linkToMaterialTheme.addMouseListener(followingLink);
        //TOD other
    }

    private class ActionFollowingLink implements MouseListener {

        @Override
        public void mouseClicked(MouseEvent e) {
            JLabel label = (JLabel) e.getSource();
            try {
                String link;
                if(label.equals(linkToVincentGithub)){
                    link = "https://github.com/vincenzopalazzo";
                }else if(label.equals(linkToMaterialTheme)){
                    link = "https://github.com/vincenzopalazzo/material-ui-swing";
                }else if(label.equals(linkToMaterialToast)){
                    link = "";
                }else{
                    link = "";
                }

                Desktop.getDesktop().browse(new URI(link));
            } catch (IOException | URISyntaxException e1) {
                e1.printStackTrace();
            }
        }

        @Override
        public void mousePressed(MouseEvent e) {

        }

        @Override
        public void mouseReleased(MouseEvent e) {

        }

        @Override
        public void mouseEntered(MouseEvent e) {
            JLabel label = (JLabel) e.getSource();
            label.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        }

        @Override
        public void mouseExited(MouseEvent e) {
            JLabel label = (JLabel) e.getSource();
            label.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }

}
